-
    Show the UoM auto enabled on website
-
  !python {model: ir.ui.view}: |
    self.write(cr, uid, [ref('product_show_uom')], {'active': True}, context={'active_test': True})
-
    Show the UoM on product list auto enabled on website
-
  !python {model: ir.ui.view}: |
    self.write(cr, uid, [ref('product_show_uom_list')], {'active': True}, context={'active_test': True})
